version: 2.1

################################
# Aliases
################################

aliases:
  - &restore_gemfile_cache
    keys:
      - v2-gemfile-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-{{ checksum "Gemfile.lock" }}
      - v2-gemfile-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-
      - v2-gemfile-{{ .Branch }}-
  - &save_gemfile_cache
    key: v2-gemfile-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-{{ checksum "Gemfile.lock" }}
    when: on_success
    paths:
      - ~/thecodechef.github.io/vendor/bundle
    

################################
# Executors
################################

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.6.1
    working_directory: '~/thecodechef.github.io'

################################
# Commands
################################

commands:
  install_gems:
    description: 'Install Gems with `bundle install`'
    steps:
      - restore_cache: *restore_gemfile_cache
      - run: gem install bundler
      - run: bundler install --path ./vendor/bundle --jobs=3 --retry=4
      - save_cache: *save_gemfile_cache

################################
# Jobs
################################

jobs:
  install:
    executor: ruby
    steps:
      - checkout
      - install_gems

################################
# Workflows
################################

workflows:
  version: 2
  test:
    jobs:
      - install
